### ISSUE TITLE
Correcciones

### ISSUE THREAD

**Issue by jesaa** [krrrunch/alaska#21]
- [x]  Prioridad productos.

- [x] Esperar enlaces redes sociales G+/Facebook.

- [x] Precio oferta se muestra erróneamente, el precio oferta se muestra tachado, normal sin tachar (Debe ser al revés).

- [x] App Códigos postales.

- [x] En las categorías (menú superior) Cuando se pase el mouse sobre la categoría mostrar las subcategorias, si se hace click en la categoría, se renderea la vista con todos los productos de la categoría.

- [x] Agregar la lista de compras a las vistas de category, manufacturer y search results

- [x] Agregar botón verde, a la lista de compras (Debe ir abajo a la derecha).

- [x] Correo para pedidos pedidos@alaska@gmail.com

- [x] Permitir agregar banner para Desktop y para movil.

@mikemotion / @leoserick

**Comment by leoserick** [comment]
- [ ] Agregar la vista metodos de Pago

- [ ] Ponerle padding al logo
