### ISSUE TITLE
Correcciones

### ISSUE THREAD

**Issue by dianem213** [krrrunch/alaska#31]
Correcciones: 

- [x] Al poner campaña ya no aparece el descuento solo el nuevo precio. 

- [x] Agregar productos al carrito desde la vista pequeña.

- [x] Al picar el botón "seguir comprando" el botón de pagar es uno distinto al verde. 

- [x] En los datos del cliente da opción a todos los estados sólo debería ser jalisco y entran en inglés.

- [x] El botón para quitar productos del carrito aun no funciona

**Comment by mikemotion** [comment]
- [ ]  Poner el total en el checkout con un gris más obscuro.

- [ ] Ajustar la navegación con tabs para que sea más ordenada, verificar tambien el funcionamiento cuando está la opción seleccionada de recoger en tienda.
![e5](https://cloud.githubusercontent.com/assets/2985080/19612382/cf144358-97ab-11e6-8dd5-362b78fea7af.png)

**Comment by mikemotion** [comment]
- [ ] No se pueden quitar productos de la lista de compras en la vista de resultados de producto.
