### ISSUE TITLE
Entrega Abarrotera

### ISSUE THREAD

**Issue by alero0d** [krrrunch/alaska#8]
## Sección: Home
- [x] ¿Tenemos en cuenta dónde agregar este texto?
En Alaska abarrotera somos una empresa de servicios dedicados a ofrecer calidad y comodidad con cada entrega al hogar de nuestros clientes. Creemos en impulsar el comercio nacional no sólo como una empresa abarrotera, sino como un servicio  de entrega a domicilio con el beneficio de ofrecer siempre precios accesibles, productos líderes y entregas a tiempo.

- [x] ¿Dónde se ve este proceso?

1. Bienvenido a Alaska abarrotera
2. Haz tu súper online
3. Confirma tu pedido y dirección
4. Paga en línea o al repartidor
5. ¡Tus compras estarán en casa en 90 minutos o menos! 

- [x] Selección de Métodos de pagos: En línea, en efectivo o Depósito, transferencia y tienda de conveniencia.

- [x] Cargar Términos y condiciones

### TÉRMINOS Y CONDICIONES

- [x] Implementar Terms como pagina 

CONDICIONES GENERALES Y SU ACEPTACIÓN 
Estas condiciones y términos generales regulan el uso del al sitio web www.alaskaabarrotera.com.mx y todas sus divisiones, subsidiarias, afiliadas y sitios de internet, la cual te ofrecen acceso al sitio web que ALASKA ABARROTERA, S.A. de C.V. pone gratuitamente a disposición de los usuarios del Internet.

El acceso al Sitio Web por parte del usuario del Servicio implica su consentimiento expreso y sin reservas a estas Condiciones Generales. Si usted no está de acuerdo con estas Condiciones Generales por favor no use el Sitio Web. 

La utilización del Servicio se encuentra sometida igualmente a todos los avisos, reglamentos de uso e instrucciones puestos en conocimiento del Usuario por ALASKA ABARROTERA. Los presentes términos y condiciones, regulan el uso del sitio web www.ALASKAABARROTERA.com.mx, del que ALASKA ABARROTERA, S.A. de C.V., es propietario, la cual es una Sociedad Anónima de Capital Variable, con domicilio en Chicalote 2750, Mercado de Abastos, Guadalajara, Jal. México 44530. 

El Usuario expresamente reconoce y acepta voluntariamente que el uso del Servicio y de los Contenidos tiene lugar, en todo caso, bajo su única y exclusiva responsabilidad.

EXCLUSIÓN DE GARANTÍAS Y DE RESPONSABILIDAD DEL SITIO WEBSITE
Privacidad y seguridad en la utilización del Servicio

ALASKA ABARROTERA SA DE CV no garantiza la privacidad y seguridad de la utilización del Servicio y, en particular, no garantiza que terceros no autorizados no puedan tener conocimiento de la clase, condiciones, características y circunstancias del uso que los Usuarios hacen del Servicio. ALASKA NO ASUME RESPONSABILIDAD ALGUNA POR LOS DAÑOS Y PERJUICIOS DE CUALQUIER NATURALEZA QUE PUDIERAN OCASIONARSE POR EL CONOCIMIENTO QUE PUEDAN TENER TERCEROS NO AUTORIZADOS DE LA CLASE, CONDICIONES, CARACTERÍSTICAS Y CIRCUNSTANCIAS DEL USO QUE LOS USUARIOS HACEN DEL SERVICIO.

Exclusión de garantías y de responsabilidad por los Contenidos
ALASKA ABARROTERA SA DE CV no controla ni garantiza la ausencia de virus ni de otros elementos en los Contenidos suministrados por ALASKA sobre la base de información proporcionada por terceros proveedores o suministrados directamente por terceros proveedores o por los Usuarios ni en cualesquiera otros contenidos proporcionados a través del Servicio que puedan producir alteraciones en su sistema informático (software y hardware) o en los documentos electrónicos y ficheros almacenados en su sistema informático. ALASKA NO ASUME RESPONSABILIDAD ALGUNA POR LOS DAÑOS Y PERJUICIOS CAUSADOS DIRECTA O INDIRECTAMENTE POR LA PRESENCIA DE VIRUS O A LA PRESENCIA DE OTROS ELEMENTOS LESIVOS EN LOS CONTENIDOS SUMINISTRADOS POR ALASKA SOBRE LA BASE DE INFORMACIÓN PROPORCIONADA POR TERCEROS PROVEEDORES, O SUMINISTRADOS DIRECTA O INDIRECTAMENTE POR TERCEROS PROVEEDORES, O POR LOS USUARIOS O EN CUALQUIER OTROS CONTENIDOS PROPORCIONADOS A TRAVÉS DEL SERVICIO QUE PUEDAN PRODUCIR ALTERACIONES EN SU SISTEMA INFORMÁTICO.

Veracidad, exactitud y actualidad.
ALASKA no garantiza de manera alguna la veracidad, exactitud y actualidad de los Contenidos suministrados por ALASKA sobre la base de información proporcionada por terceros proveedores o suministrados directamente por terceros proveedores o por otros Usuarios ni de cualesquiera otros contenidos proporcionados a través del Servicio. POR LO ANTERIOR, ALASKA NO ASUME RESPONSABILIDAD ALGUNA POR LOS DAÑOS Y PERJUICIOS DE CUALQUIER NATURALEZA QUE PUEDAN CAUSARSE POR LA FALTA DE VERACIDAD, EXACTITUD, Y/O ACTUALIDAD DE LOS CONTENIDOS TRANSMITIDOS, DIFUNDIDOS, ALMACENADOS, PUESTOS A DISPOSICIÓN O RECIBIDOS, OBTENIDOS O A LOS QUE SE HAYA ACCEDIDO A TRAVÉS DEL SERVICIO.

DENEGACIÓN Y RETIRADA DEL ACCESO AL WEBSITE Y/O A LOS SERVICIOS 
ALASKA se reserva el derecho a denegar o retirar el acceso al Servicio, en cualquier momento y sin necesidad de aviso previo, a aquellos Usuarios que incumplan estas Condiciones Generales.

ENVÍO DE PROMOCIONES Y OFERTAS 
Durante el proceso de registro, aceptas recibir correos electrónicos promocionales del sitio www.ALASKAABARROTERA.com.mx.

RESPONSABILIDAD
Hay casos en los cuales una orden de compra puede no ser procesada por circunstancias ajenas a nosotros y las cuales no pueden ser previstas, circunstancias en las cuales interviene la fuerza mayor o el caso fortuito, en ese sentido, www.ALASKAABARROTERA.com.mx, informará al cliente de inmediato el motivo por el cual no fue posible procesar una orden, restituyendo cualquier cantidad cobrada al usuario, dejando claro que en este proceso se puede pedir información adicional para completar el proceso de reembolso.

AUTENTICIDAD
Certificamos que cualquier producto que usted adquiere en nuestra tienda en línea es original y está comercializado bajo las licencias correspondiente de calidad y origen.

PROMOCIONES  
Todas las promociones no son acumulable con otras promociones. Aplican hasta agotar existencias y están restringidas a una por persona.

**Comment by alero0d** [comment]
- [ ] Encuesta de calidad que se encuentra:
https://drive.google.com/file/d/0B-KR19HC50S5LWFUWXJWel96U2s/view?usp=sharing

**Comment by alero0d** [comment]
- [ ] Códigos Postales: https://docs.google.com/spreadsheets/d/1qQhKZJy8hyePMoqDoGbxaYsC6r0xs9T_uwHjpkKUcy0/edit#gid=0

**Comment by leoserick** [comment]
## Schema Data Structure
Resolver con variables de Lite cart la impresión de :
`<div itemscope itemtype="https://schema.org/Organization" class="sr-only">
  <div itemprop="legalName">Alaska</div>
  <div itemprop="description">#todo</div>
  <div itemprop="address">#todo</div>
  <div itemprop="areaServed">#todo</div>
  <div itemprop="telephone">#todo</div>
</div>`
en las interfaces:

- box_category.inc
- box_most_popular_products.inc
-box_similar_products.inc

(No estoy seguro de que sean todas las interfaces en las que se necesite modificar la implementación pero si alguien encuentra otra agregarla a la lista (Importante agregarla para tener un listado de interfaces donde se tiene esta estructura de datos ))

**Comment by leoserick** [comment]
_@alero0d  @mikemotion  Los términos y condiciones tienen mucho texto en Uppercase_

**Comment by leoserick** [comment]
@alero0d @mikemotion Necesitamos la sección de Nosotros, no tenemos esa información y tenemos la pagina creada en Lite Cart y se muestra.

- [ ]  Resolver la información con el cliente acerca de Nosotros
